### PR TITLE
dk-rework

### PR DESCRIPTION
**Pull request by mkPrieur**
side b barrel changes
fair changes

### CODE REVIEW

**Comment by mkPrieur** [comment]
Donkey Kong with a new sideb - Barrel:

The barrel is automatically thrown
Startup - 33
Damage - 10
BKB - 15
KBG - 80

Donkey Kong with a new fair - Spin Punch:

DK spins during the punch and faces the opposite way at the end of the animation
Startup - 10
Damage - 9
Angle - 60
BKB - 45
KBG - 85

[Ultimate S Arcropolis.zip](https://github.com/chrispo-git/ult-s/files/9551666/Ultimate.S.Arcropolis.zip)

**Comment by chrispo-git** [comment]
playing w/ it rn, DK seems to face the wrong way at the end of the bair anim, and transitioning into fall just snaps his model into the proper anim

honestly there are too many possible kb values on this fair
theres sweetspot, sour, super sour, late sweetspot, late sour
super sour frankly shouldnt be there
and honestly the late hit doesnt need to be a thing on something with a sweetspot either
if i were to recommend anything i'd say just make the entire move have the same kb as early sweetspot does

**Comment by chrispo-git** [comment]
also probably make hitboxes larger, it literally cant hit ryu rising, which it probably should

**Comment by mkPrieur** [comment]
[Ultimate S Arcropolis.zip](https://github.com/chrispo-git/ult-s/files/9591940/Ultimate.S.Arcropolis.zip)

Donkey Kong with a new sideb - Barrel:

The barrel is automatically thrown
Startup - 33
Damage - 10
BKB - 15
KBG - 80

Donkey Kong with a new fair - Spin Punch:

DK spins during the punch and faces the opposite way at the end of the animation
Startup - 10
Damage - 9
Angle - 60
BKB - 45
KBG - 85

**Comment by mkPrieur** [comment]
UPDATED DOWNLOAD!!:

[Ultimate S Arcropolis.zip](https://github.com/chrispo-git/ult-s/files/9625551/Ultimate.S.Arcropolis.zip)

**Pull request closed without merging**
